### ISSUE TITLE
TemplateDoesNotExist Exception Value:	 bulma/layout/fieldset.html

### ISSUE THREAD

**Issue by kalevhark** [ckrybus/crispy-bulma#14]
Django 5.0
django-crispy-forms 2.1
crispy-bulma 0.11.0

in template:
{% load crispy_forms_tags %}
{{ form|crispy }}

TemplateDoesNotExist bulma/layout/fieldset.html

**Comment by ckrybus** [comment]
Hi @kalevhark, fieldsets are not supported yet :-( 

Right now I don't have time to implement it, but you are welcome to create a pull request. There are old fieldset tests (`@pytest.mark.skip(reason="fieldset")`) which you can use as a starting point.

**Comment by kalevhark** [comment]
> Hi @kalevhark, fieldsets are not supported yet :-(
> 
> Right now I don't have time to implement it, but you are welcome to create a pull request. There are old fieldset tests (`@pytest.mark.skip(reason="fieldset")`) which you can use as a starting point.

I "borrowed" fieldset.html and buttonholder.html from other packages and it seems to work as well :-) Happy New Year!

**Comment by ckrybus** [comment]
Closing as this was implemented in #15 (will be released probably in the next few days, right now only available on `main`)

**Comment by leolivier** [comment]
Hi @ckrybus 
You said above it would be delivered a few days after Mar 28, 2024 but more than one year later, the PR is merged but is not yet released.
No offense, but is this project still alive?
