### ISSUE TITLE
Inline error text <p> tag styled using the wrong class

### ISSUE THREAD

**Issue by jayqi** [ckrybus/crispy-bulma#17]
When displaying a field error inline, the following `<p>` tag HTML is added:

https://github.com/ckrybus/crispy-bulma/blob/2e9abb011f0b5b9cf0dbc8a6def1cec8a44568c1/crispy_bulma/templates/bulma/field.html#L56-L59

The `is-danger` class used here is not correct. `is-danger` doesn't actually do anything for a `<p>` tag. 

Instead, Bulma has the `has-text-danger` CSS helper class for changing the text color in a general container element. ([docs](https://bulma.io/documentation/helpers/color-helpers/#text-color))

Using:
- `crispy-bulma==0.11.0`
- `bulma@1.0.2`

**Comment by ckrybus** [comment]
Hi @jayqi, thanks for reporting this!

> is-danger doesn't actually do anything for a `<p>` tag.

Visually it is the same, by default the text is rendered in red, so it does work (at least inside a form).

> The is-danger class used here is not correct. 

The [bulma docs](https://bulma.io/documentation/form/general/) display the form errors using `is-danger`, see the screenshot below:

![bulma](https://github.com/user-attachments/assets/1d8cb328-c608-4145-b815-a23b8aaa8839)
