### ISSUE TITLE
Some widgets unsupported

### ISSUE THREAD

**Issue by pythonbrad** [ckrybus/crispy-bulma#2]
###  Some widgets are not styled.
- django.forms.widgets.DateInput
- django.forms.widgets.DateTimeInput
- django.forms.widgets.NumberInput
- django.forms.widgets.TextInput
- django.forms.widgets.ClearableFileInput
- django.forms.widgets.SplitDateTimeWidget
- django.forms.widgets.TimeInput
- django.forms.widgets.URLInput
### Some widgets are not styled properly
- crispy_bulma.widgets.FileUploadInput
### System Configuration 
- Bulma 0.9.3
- Django 4.1.4
- crispy-bulma 0.8.0
- django-crispy-forms 1.14.0

---

**Update 2022-12-29:**

- :heavy_check_mark:  django.forms.widgets.DateInput
- :heavy_check_mark: django.forms.widgets.DateTimeInput
- :heavy_check_mark:  django.forms.widgets.NumberInput
- :heavy_check_mark:  django.forms.widgets.TextInput
- :white_check_mark:  django.forms.widgets.ClearableFileInput (explicit use of [FileUploadInput](https://github.com/ckrybus/crispy-bulma/blob/ddbb420e649a572b5db1f55f84375824835d37ce/crispy_bulma/widgets.py#L4) widget for now)
- :negative_squared_cross_mark:   django.forms.widgets.SplitDateTimeWidget (#5 )
-  :heavy_check_mark: django.forms.widgets.TimeInput
-  :heavy_check_mark: django.forms.widgets.URLInput
-  :heavy_check_mark: crispy_bulma.widgets.FileUploadInput

**Comment by ckrybus** [comment]
Hi @pythonbrad,

I did not check all the widgets you listed, but they should work. [Here](https://github.com/django-crispy-forms/crispy-test-project/pull/33) is a small demo how a rendered form looks like.

I suspect that you did not include [bulma.css](https://bulma.io/documentation/overview/start/) in your `base.html` template. Here is an example:

```html
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
  </head>
```

**Comment by pythonbrad** [comment]
> [Here](https://github.com/django-crispy-forms/crispy-test-project/pull/33) is a small demo how a rendered form looks like.

I tried to update the demonstration to use the crispy_bulma.widgets.FileUploadInput widget.
Available [Here](https://github.com/ckrybus/crispy-test-project/pull/1)

### What is change ?
![a](https://user-images.githubusercontent.com/45305909/207524708-4485595c-cbbc-496d-8c1f-bc70e0cc34b6.png)

![b](https://user-images.githubusercontent.com/45305909/207524754-3de6a07b-d55e-4ecc-8875-af451074f0c9.png)

**Comment by pythonbrad** [comment]
The following widgets can be fixed in using of `widget=forms.TextInput(attrs={'type': '<type>'})`
- django.forms.widgets.DateInput
- django.forms.widgets.DateTimeInput
- django.forms.widgets.NumberInput
- django.forms.widgets.TextInput
- django.forms.widgets.TimeInput
- django.forms.widgets.URLInput
### Preview
*NB*: Just Date, Datetime, and Time is rendered using only the trick (TextInput).
* Left: Before, Right: After
![a](https://user-images.githubusercontent.com/45305909/207529229-4351dd06-699c-4856-b143-ee6b898232ba.png)

**Comment by ckrybus** [comment]
@pythonbrad all widgets except SplitDateTimeWidget (issue #5) should work now in the main branch.
For now FileField (ClearableFileInput, FileInput) is styled correctly only when the newly fixed FileUploadInput widget is being explicitely used.
